- name: "articles"
  label: "Статьи"
  folder: "articles"
  create: true
  slug: "{{slug}}"
  summary: "{{title}} — {{date}}"
  preview_path: "article/{{slug}}"
  fields:
    - { label: "Заголовок", name: "title", widget: "string" }
    - { label: "Дата", name: "date", widget: "datetime" }
    - { label: "Текст", name: "body", widget: "markdown" }
