backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey  # можно удалить или заменить на 'cloudinary', если не нужен uploadcare

collections:
  - name: "articles"
    label: "Статьи"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Текст", name: "body", widget: "markdown" }
